### List all games
GET http://localhost:5115/games


### Invoke a specific game by ID
GET http://localhost:5115/games/8

### Create a new game
POST http://localhost:5115/games
Content-Type: application/json

{
    "Name": "The Legend of Zelda: Breath of the Wild",
    "genre": "Action-adventure",
    "price": 200,
    "releaseDate": "2017-03-03"
}

### Update a specific game by ID
PUT http://localhost:5115/games/8
Content-Type: application/json

{
    "name": "Super Mario Bros.",
    "genre": "Platformer",
    "price": 39.99,
    "releaseDate": "1985-09-13"
}

### Delete a specific game by ID
DELETE  http://localhost:5115/games/2